# Generated by Django 5.0.3 on 2024-04-11 06:53

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chiPhi', models.FloatField(default=0)),
                ('ngayDi', models.DateTimeField()),
                ('ngayDen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JourneyPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('picture', cloudinary.models.CloudinaryField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaChi', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('reportContent', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='Hanh Trinh', max_length=255),
        ),
        migrations.AlterField(
            model_name='travelcompanion',
            name='timeselect',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=255)),
                ('cmtRep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reply', to='ShareJourneysApp.comments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('cmtTick', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ShareJourneysApp.comments')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='pic',
            field=models.ManyToManyField(related_name='pictures', to='ShareJourneysApp.journeypictures'),
        ),
        migrations.CreateModel(
            name='DiaDiemDungChan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoiGianDung', models.IntegerField(default=1)),
                ('id_HanhTrinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hanhTrinh', to='ShareJourneysApp.journey')),
                ('id_DiaDiem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaDiem', to='ShareJourneysApp.local')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_noiDen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noiDen', to='ShareJourneysApp.local')),
                ('id_noiDi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noiDi', to='ShareJourneysApp.local')),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='id_tuyenDuong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tuyenDuong', to='ShareJourneysApp.route'),
        ),
        migrations.AddField(
            model_name='posts',
            name='tags',
            field=models.ManyToManyField(to='ShareJourneysApp.tag'),
        ),
        migrations.AddField(
            model_name='journey',
            name='id_PhuongTien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phuongTien', to='ShareJourneysApp.transportation'),
        ),
        migrations.CreateModel(
            name='Users_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='ShareJourneysApp.reports')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='JournyPictures',
        ),
    ]
