# Generated by Django 5.0.3 on 2024-04-24 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0002_journey_journeypictures_local_reports_tag_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commenttick',
            name='cmtTick',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='ShareJourneysApp.comments'),
        ),
    ]
