# Generated by Django 5.0.3 on 2024-06-20 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0004_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_NV',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postuserNV', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='postuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
