# Generated by Django 5.0.3 on 2024-06-20 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0006_posts_journey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diadiemdungchan',
            name='thoiGianDung',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
