# Generated by Django 5.0.3 on 2024-06-25 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0007_alter_diadiemdungchan_thoigiandung'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('id_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('id_noiDen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noiDen', to='ShareJourneysApp.diadiemdungchan')),
                ('id_noiDi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noiDi', to='ShareJourneysApp.diadiemdungchan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
