# Generated by Django 5.0.3 on 2024-06-25 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0008_userroute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroute',
            name='id_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRoute', to='ShareJourneysApp.travelcompanion'),
        ),
    ]
