# Generated by Django 5.0.3 on 2024-06-25 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0009_alter_userroute_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userroute',
            name='id_noiDen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noiDen', to='ShareJourneysApp.diadiemdungchan'),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='id_noiDi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noiDi', to='ShareJourneysApp.diadiemdungchan'),
        ),
    ]
