# Generated by Django 5.0.3 on 2024-06-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShareJourneysApp', '0010_alter_userroute_id_noiden_alter_userroute_id_noidi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroute',
            name='id_noiDen',
        ),
        migrations.RemoveField(
            model_name='userroute',
            name='id_noiDi',
        ),
        migrations.AddField(
            model_name='userroute',
            name='id_Den',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Den', to='ShareJourneysApp.local'),
        ),
        migrations.AddField(
            model_name='userroute',
            name='id_Don',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noiDon', to='ShareJourneysApp.local'),
        ),
        migrations.AlterField(
            model_name='travelcompanion',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userroute',
            name='id_User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userRoute', to='ShareJourneysApp.travelcompanion'),
        ),
    ]
